# Generated by Django 5.1 on 2026-03-24 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('collectes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommandeDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantite', models.PositiveIntegerField()),
                ('unite_vente', models.CharField(max_length=20)),
                ('sous_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('est_disponible', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Detail commande',
                'verbose_name_plural': 'Details commande',
            },
        ),
        migrations.CreateModel(
            name='HistoriqueStatutCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut_avant', models.CharField(max_length=20)),
                ('statut_apres', models.CharField(max_length=20)),
                ('commentaire', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Historique statut',
                'verbose_name_plural': 'Historiques statuts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_commande', models.CharField(blank=True, max_length=30, unique=True)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente de confirmation'), ('confirmee', 'Confirmee'), ('en_preparation', 'En preparation'), ('prete', 'Prete pour collecte'), ('en_collecte', 'En cours de collecte'), ('livree', 'Livree'), ('annulee', 'Annulee'), ('litige', 'En litige')], default='en_attente', max_length=20)),
                ('statut_paiement', models.CharField(choices=[('non_paye', 'Non paye'), ('en_attente', 'En attente de verification'), ('preuve_soumise', 'Preuve soumise'), ('verifie', 'Verifie'), ('paye', 'Paye'), ('rembourse', 'Rembourse')], default='non_paye', max_length=20)),
                ('methode_paiement', models.CharField(choices=[('moncash', 'MonCash'), ('natcash', 'NatCash'), ('virement', 'Virement bancaire'), ('cash', 'Especes'), ('voucher', 'e-Voucher')], max_length=20)),
                ('preuve_paiement', models.ImageField(blank=True, null=True, upload_to='commandes/preuves/')),
                ('reference_paiement', models.CharField(blank=True, max_length=100)),
                ('sous_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('frais_livraison', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('remise', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('mode_livraison', models.CharField(choices=[('domicile', 'Livraison a domicile'), ('retrait', 'Retrait chez le producteur'), ('collecte', 'Point de collecte')], default='collecte', max_length=20)),
                ('adresse_livraison', models.TextField(blank=True)),
                ('ville_livraison', models.CharField(blank=True, max_length=100)),
                ('departement_livraison', models.CharField(blank=True, max_length=100)),
                ('notes_acheteur', models.TextField(blank=True)),
                ('notes_admin', models.TextField(blank=True)),
                ('date_confirmation', models.DateTimeField(blank=True, null=True)),
                ('date_livraison_prevue', models.DateField(blank=True, null=True)),
                ('date_livraison_reelle', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('acheteur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commandes', to='accounts.acheteur')),
                ('collecte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes', to='collectes.collecte')),
                ('producteur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commandes_recues', to='accounts.producteur')),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
                'ordering': ['-created_at'],
            },
        ),
    ]
