# Generated by Django 5.1 on 2026-03-24 10:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('orders', '0001_initial'),
        ('payments', '0001_initial'),
        ('stock', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='voucher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commandes', to='payments.voucher'),
        ),
        migrations.AddField(
            model_name='commandedetail',
            name='commande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='orders.commande'),
        ),
        migrations.AddField(
            model_name='commandedetail',
            name='lot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lignes_commande', to='stock.lot'),
        ),
        migrations.AddField(
            model_name='commandedetail',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_commande', to='catalog.produit'),
        ),
        migrations.AddField(
            model_name='historiquestatutcommande',
            name='commande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_statuts', to='orders.commande'),
        ),
        migrations.AddField(
            model_name='historiquestatutcommande',
            name='effectue_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
