# Generated by Django 5.2.12 on 2026-03-25 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='methode_paiement',
            field=models.CharField(choices=[('moncash', 'MonCash'), ('natcash', 'NatCash'), ('virement', 'Virement bancaire'), ('cash', 'Especes'), ('voucher', 'e-Voucher'), ('hors_ligne', 'Paiement hors ligne')], max_length=20),
        ),
    ]
