# Generated by Django 5.2.12 on 2026-07-07 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_panier_lignepanier_delete_panieritem'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='montant_wallet_utilise',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Solde wallet réservé sur cette commande (paiement partiel) — le complément part vers MonCash/NatCash.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='commande',
            name='methode_paiement',
            field=models.CharField(choices=[('moncash', 'MonCash'), ('natcash', 'NatCash'), ('virement', 'Virement bancaire'), ('cash', 'Especes'), ('voucher', 'e-Voucher'), ('hors_ligne', 'Paiement hors ligne'), ('wallet', 'Portefeuille')], max_length=20),
        ),
    ]
