# Generated by Django 5.1 on 2026-03-24 10:10

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acheteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_acheteur', models.CharField(choices=[('particulier', 'Particulier'), ('grossiste', 'Grossiste'), ('detaillant', 'Detaillant'), ('cooperative', 'Cooperative'), ('institution', 'Institution / ONG'), ('restaurant', 'Restaurant / Hotel')], default='particulier', max_length=20)),
                ('nom_organisation', models.CharField(blank=True, max_length=200)),
                ('adresse', models.TextField(blank=True)),
                ('ville', models.CharField(blank=True, max_length=100)),
                ('departement', models.CharField(blank=True, max_length=100)),
                ('total_commandes', models.PositiveIntegerField(default=0)),
                ('total_depense', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Acheteur',
                'verbose_name_plural': 'Acheteurs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Producteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departement', models.CharField(choices=[('ouest', 'Ouest'), ('sud_est', 'Sud-Est'), ('nord', 'Nord'), ('nord_est', 'Nord-Est'), ('artibonite', 'Artibonite'), ('centre', 'Centre'), ('sud', 'Sud'), ('grand_anse', 'Grand-Anse'), ('nord_ouest', 'Nord-Ouest'), ('nippes', 'Nippes')], max_length=20)),
                ('commune', models.CharField(max_length=100)),
                ('localite', models.CharField(blank=True, max_length=100)),
                ('adresse_complete', models.TextField(blank=True)),
                ('superficie_ha', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('description', models.TextField(blank=True)),
                ('code_producteur', models.CharField(blank=True, max_length=20, unique=True)),
                ('num_identification', models.CharField(blank=True, max_length=50)),
                ('photo_identite', models.ImageField(blank=True, null=True, upload_to='producteurs/identites/')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente de validation'), ('actif', 'Actif'), ('suspendu', 'Suspendu'), ('inactif', 'Inactif')], default='en_attente', max_length=20)),
                ('note_admin', models.TextField(blank=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Producteur',
                'verbose_name_plural': 'Producteurs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('superadmin', 'Super Administrateur'), ('admin', 'Administrateur'), ('producteur', 'Producteur'), ('acheteur', 'Acheteur'), ('collecteur', 'Agent de Collecte')], default='acheteur', max_length=20)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='users/photos/')),
                ('is_verified', models.BooleanField(default=False)),
                ('fcm_token', models.TextField(blank=True, help_text='Firebase token pour notifications push')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'ordering': ['-created_at'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
