# Generated by Django 5.1 on 2026-03-24 10:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='acheteur',
            name='categories_preferees',
            field=models.ManyToManyField(blank=True, related_name='acheteurs_interesses', to='catalog.categorie'),
        ),
        migrations.AddField(
            model_name='acheteur',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_acheteur', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='producteur',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_producteur', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='producteur',
            name='valide_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='producteurs_valides', to=settings.AUTH_USER_MODEL),
        ),
    ]
