# Generated by Django 5.2.12 on 2026-03-24 18:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adresse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(help_text='Ex : Domicile, Bureau…', max_length=100, verbose_name='Libellé')),
                ('nom_complet', models.CharField(max_length=150, verbose_name='Nom complet du destinataire')),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('rue', models.CharField(max_length=255, verbose_name='Rue / Adresse')),
                ('commune', models.CharField(max_length=100, verbose_name='Commune')),
                ('departement', models.CharField(choices=[('ouest', 'Ouest'), ('sud_est', 'Sud-Est'), ('nord', 'Nord'), ('nord_est', 'Nord-Est'), ('artibonite', 'Artibonite'), ('centre', 'Centre'), ('sud', 'Sud'), ('grand_anse', 'Grand-Anse'), ('nord_ouest', 'Nord-Ouest'), ('nippes', 'Nippes')], max_length=20, verbose_name='Département')),
                ('ville', models.CharField(blank=True, max_length=100, verbose_name='Ville')),
                ('details', models.TextField(blank=True, verbose_name='Instructions de livraison')),
                ('type_adresse', models.CharField(choices=[('livraison', 'Livraison'), ('facturation', 'Facturation')], default='livraison', max_length=20, verbose_name='Type')),
                ('is_default', models.BooleanField(default=False, verbose_name='Adresse par défaut')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Adresse',
                'verbose_name_plural': 'Adresses',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
    ]
