# Generated by Django 5.2.12 on 2026-03-27 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_adresse_section_communale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Administrateur'), ('producteur', 'Producteur'), ('acheteur', 'Acheteur'), ('collecteur', 'Agent de Collecte')], default='acheteur', max_length=20),
        ),
    ]
