# Generated by Django 5.2.12 on 2026-07-07 17:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='code_parrainage',
            field=models.CharField(blank=True, help_text='Code à partager — généré à la demande (wallet).', max_length=12, null=True, unique=True, verbose_name='Code de parrainage'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='parraine_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filleuls', to=settings.AUTH_USER_MODEL, verbose_name='Parrainé par'),
        ),
    ]
