# Generated by Django 5.2.12 on 2026-07-10 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customuser_code_parrainage_customuser_parraine_par'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Administrateur'), ('producteur', 'Producteur'), ('acheteur', 'Acheteur'), ('collecteur', 'Agent de Collecte'), ('pos_operator', 'Opérateur de caisse')], default='acheteur', max_length=20),
        ),
    ]
