# Generated by Django 5.1 on 2026-03-24 10:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('collectes', '0001_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_lot', models.CharField(blank=True, max_length=50, unique=True)),
                ('code_barres', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('quantite_initiale', models.PositiveIntegerField()),
                ('quantite_actuelle', models.PositiveIntegerField()),
                ('quantite_vendue', models.PositiveIntegerField(default=0)),
                ('date_recolte', models.DateField(blank=True, null=True)),
                ('date_expiration', models.DateField(blank=True, null=True)),
                ('lieu_stockage', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('disponible', 'Disponible'), ('epuise', 'Epuise'), ('expire', 'Expire'), ('rappel', 'Rappele')], default='disponible', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lots_crees', to=settings.AUTH_USER_MODEL)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lots', to='catalog.produit')),
            ],
            options={
                'verbose_name': 'Lot',
                'verbose_name_plural': 'Lots',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AlerteStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau', models.CharField(choices=[('info', 'Information'), ('warning', 'Avertissement'), ('critique', 'Critique — Stock tres faible'), ('epuise', 'Epuise')], default='warning', max_length=20)),
                ('statut', models.CharField(choices=[('nouvelle', 'Nouvelle'), ('vue', 'Vue'), ('en_cours', 'En cours de traitement'), ('resolue', 'Resolue'), ('ignoree', 'Ignoree')], default='nouvelle', max_length=20)),
                ('stock_actuel', models.PositiveIntegerField()),
                ('seuil', models.PositiveIntegerField()),
                ('message', models.TextField()),
                ('note_traitement', models.TextField(blank=True)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertes_stock', to='catalog.produit')),
                ('traitee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertes_traitees', to=settings.AUTH_USER_MODEL)),
                ('lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertes', to='stock.lot')),
            ],
            options={
                'verbose_name': 'Alerte stock',
                'verbose_name_plural': 'Alertes stock',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MouvementStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_mouvement', models.CharField(choices=[('entree', 'Entree — Nouvelle recolte'), ('sortie_vente', 'Sortie — Vente'), ('sortie_collecte', 'Sortie — Collecte'), ('ajust_pos', 'Ajustement positif'), ('ajust_neg', 'Ajustement negatif'), ('perte', 'Perte / Deterioration'), ('retour', 'Retour client'), ('transfert', 'Transfert de lot')], max_length=20)),
                ('quantite', models.PositiveIntegerField()),
                ('stock_avant', models.PositiveIntegerField()),
                ('stock_apres', models.PositiveIntegerField()),
                ('motif', models.TextField(blank=True)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collecte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_stock', to='collectes.collecte')),
                ('commande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_stock', to='orders.commande')),
                ('effectue_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mouvements_effectues', to=settings.AUTH_USER_MODEL)),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='stock.lot')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements_stock', to='catalog.produit')),
            ],
            options={
                'verbose_name': 'Mouvement de stock',
                'verbose_name_plural': 'Mouvements de stock',
                'ordering': ['-created_at'],
            },
        ),
    ]
