# Generated by Django 5.1 on 2026-03-24 10:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PointCollecte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('adresse', models.TextField()),
                ('commune', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('responsable', models.CharField(blank=True, max_length=200)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Point de collecte',
                'verbose_name_plural': 'Points de collecte',
                'ordering': ['zone', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='ZoneCollecte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('departement', models.CharField(choices=[('ouest', 'Ouest'), ('sud_est', 'Sud-Est'), ('nord', 'Nord'), ('nord_est', 'Nord-Est'), ('artibonite', 'Artibonite'), ('centre', 'Centre'), ('sud', 'Sud'), ('grand_anse', 'Grand-Anse'), ('nord_ouest', 'Nord-Ouest'), ('nippes', 'Nippes')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Zone de collecte',
                'verbose_name_plural': 'Zones de collecte',
                'ordering': ['departement', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Collecte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=30, unique=True)),
                ('date_planifiee', models.DateField()),
                ('heure_debut', models.TimeField(blank=True, null=True)),
                ('heure_fin', models.TimeField(blank=True, null=True)),
                ('date_debut_reel', models.DateTimeField(blank=True, null=True)),
                ('date_fin_reel', models.DateTimeField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('planifiee', 'Planifiee'), ('en_cours', 'En cours'), ('terminee', 'Terminee'), ('annulee', 'Annulee'), ('reportee', 'Reportee')], default='planifiee', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('rapport', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collecteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collectes_assignees', to=settings.AUTH_USER_MODEL)),
                ('point_collecte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collectes', to='collectes.pointcollecte')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collectes', to='collectes.zonecollecte')),
            ],
            options={
                'verbose_name': 'Collecte',
                'verbose_name_plural': 'Collectes',
                'ordering': ['-date_planifiee'],
            },
        ),
        migrations.AddField(
            model_name='pointcollecte',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='collectes.zonecollecte'),
        ),
        migrations.CreateModel(
            name='ParticipationCollecte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(choices=[('inscrit', 'Inscrit'), ('confirme', 'Confirme'), ('present', 'Present'), ('absent', 'Absent'), ('annule', 'Annule')], default='inscrit', max_length=20)),
                ('quantite_prevue', models.PositiveIntegerField(default=0, help_text='Quantite estimee a apporter (kg ou unites)')),
                ('quantite_collectee', models.PositiveIntegerField(default=0, help_text='Quantite reellement collectee')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('collecte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='collectes.collecte')),
                ('producteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations_collectes', to='accounts.producteur')),
            ],
            options={
                'verbose_name': 'Participation collecte',
                'verbose_name_plural': 'Participations collectes',
                'ordering': ['-created_at'],
                'unique_together': {('collecte', 'producteur')},
            },
        ),
    ]
