# Generated by Django 5.2.12 on 2026-03-24 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom complet')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('sujet', models.CharField(max_length=200, verbose_name='Sujet')),
                ('message', models.TextField(verbose_name='Message')),
                ('est_lu', models.BooleanField(default=False, verbose_name='Lu')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Reçu le')),
            ],
            options={
                'verbose_name': 'Message de contact',
                'verbose_name_plural': 'Messages de contact',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FAQCategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100, verbose_name='Titre de la catégorie')),
                ('icone', models.CharField(blank=True, help_text='Ex: fas fa-question-circle', max_length=60, verbose_name='Icône Font Awesome')),
                ('ordre', models.PositiveSmallIntegerField(default=0, verbose_name='Ordre')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Catégorie FAQ',
                'verbose_name_plural': 'Catégories FAQ',
                'ordering': ['ordre', 'titre'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_site', models.CharField(default='Makèt Peyizan', max_length=100, verbose_name='Nom du site')),
                ('slogan', models.CharField(default='Marketplace Agricole Haïtienne', max_length=200, verbose_name='Slogan / sous-titre')),
                ('logo', models.ImageField(blank=True, help_text='Recommandé : PNG transparent, 200×60 px minimum', null=True, upload_to='site/logo/', verbose_name='Logo')),
                ('favicon', models.ImageField(blank=True, help_text='ICO ou PNG 32×32 px', null=True, upload_to='site/favicon/', verbose_name='Favicon')),
                ('hero_badge_texte', models.CharField(blank=True, default='Marketplace Agricole Haïtienne', max_length=100, verbose_name='Texte du badge hero')),
                ('hero_titre_ligne1', models.CharField(blank=True, default='Sòti nan jaden', max_length=200, verbose_name='Hero — titre ligne 1')),
                ('hero_titre_ligne2', models.CharField(blank=True, default='rive lakay ou', max_length=200, verbose_name='Hero — titre ligne 2')),
                ('hero_sous_titre', models.TextField(blank=True, default="Manje m se medikaman m — Achetez directement auprès des producteurs locaux. Produits frais, traçables, livrés depuis les champs d'Haïti.", verbose_name='Hero — sous-titre')),
                ('a_propos_titre', models.CharField(blank=True, default='À propos de Makèt Peyizan', max_length=200, verbose_name='Titre de la page À propos')),
                ('a_propos_contenu', models.TextField(blank=True, help_text='Texte principal de la page À propos', verbose_name='Présentation générale')),
                ('a_propos_mission', models.TextField(blank=True, verbose_name='Notre mission')),
                ('a_propos_vision', models.TextField(blank=True, verbose_name='Notre vision')),
                ('a_propos_image', models.ImageField(blank=True, null=True, upload_to='site/apropos/', verbose_name='Image À propos')),
                ('annee_fondation', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Année de fondation')),
                ('email_contact', models.EmailField(blank=True, default='info@maketpeyizan.ht', max_length=254, verbose_name='Email de contact')),
                ('telephone', models.CharField(blank=True, max_length=30, verbose_name='Téléphone')),
                ('whatsapp', models.CharField(blank=True, help_text='Numéro avec indicatif ex: +509 XXXX-XXXX', max_length=30, verbose_name='WhatsApp')),
                ('adresse', models.TextField(blank=True, verbose_name='Adresse physique')),
                ('horaires', models.CharField(blank=True, help_text='Ex: Lun–Ven 8h–17h', max_length=200, verbose_name="Horaires d'ouverture")),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook URL')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram URL')),
                ('twitter_url', models.URLField(blank=True, verbose_name='Twitter / X URL')),
                ('youtube_url', models.URLField(blank=True, verbose_name='YouTube URL')),
                ('copyright_texte', models.CharField(blank=True, default='Makèt Peyizan Haiti. Tous droits réservés.', max_length=300, verbose_name='Texte copyright')),
                ('meta_description', models.TextField(blank=True, help_text='160 caractères max recommandé', verbose_name='Meta description (SEO)')),
                ('google_analytics_id', models.CharField(blank=True, help_text='Format : G-XXXXXXXXXX', max_length=50, verbose_name='Google Analytics ID')),
                ('mode_maintenance', models.BooleanField(default=False, help_text='Active une page de maintenance pour les visiteurs', verbose_name='Mode maintenance')),
                ('message_maintenance', models.TextField(blank=True, help_text='Message affiché pendant la maintenance', verbose_name='Message de maintenance')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuration du site',
                'verbose_name_plural': 'Configuration du site',
            },
        ),
        migrations.CreateModel(
            name='FAQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=400, verbose_name='Question')),
                ('reponse', models.TextField(verbose_name='Réponse')),
                ('ordre', models.PositiveSmallIntegerField(default=0, verbose_name='Ordre')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.faqcategorie', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Question FAQ',
                'verbose_name_plural': 'Questions FAQ',
                'ordering': ['categorie__ordre', 'ordre'],
            },
        ),
    ]
