# Generated by Django 5.2.12 on 2026-03-24 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='login_image',
            field=models.ImageField(blank=True, help_text='Panneau gauche de la page de connexion. Recommandé : 800×1000 px', null=True, upload_to='site/auth/', verbose_name='Image page Connexion'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='register_image',
            field=models.ImageField(blank=True, help_text="Panneau gauche de la page d'inscription. Recommandé : 800×1000 px", null=True, upload_to='site/auth/', verbose_name='Image page Inscription'),
        ),
    ]
