# Generated by Django 5.2.12 on 2026-07-07 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_android_apk'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='cashback_enabled',
            field=models.BooleanField(default=False, help_text="Crédite un pourcentage de chaque commande payée sur le wallet de l'acheteur.", verbose_name='Activer le cashback'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='numero_moncash_depot',
            field=models.CharField(blank=True, help_text='Compte MonCash de la plateforme où les clients déposent pour recharger leur wallet.', max_length=30, verbose_name='Numéro MonCash (dépôts hors ligne)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='numero_natcash_depot',
            field=models.CharField(blank=True, help_text='Compte NatCash de la plateforme où les clients déposent pour recharger leur wallet.', max_length=30, verbose_name='Numéro NatCash (dépôts hors ligne)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='parrainage_enabled',
            field=models.BooleanField(default=False, help_text='Bonus wallet au parrain et au filleul à la première commande payée du filleul.', verbose_name='Activer le parrainage'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='taux_bonus_parrainage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Pourcentage du montant de la première commande, crédité au parrain ET au filleul.', max_digits=5, verbose_name='Bonus parrainage (%)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='taux_cashback',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Taux de cashback (%)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='taux_commission',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Pourcentage prélevé sur les ventes créditées au wallet des producteurs. 0 = pas de commission.', max_digits=5, verbose_name='Commission plateforme (%)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='wallet_enabled',
            field=models.BooleanField(default=False, help_text='Active le wallet (recharges, paiements, retraits) pour les acheteurs et producteurs.', verbose_name='Activer le portefeuille'),
        ),
    ]
