# Generated by Django 5.2.12 on 2026-07-09 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_sitesettings_cashback_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='cashback_montant_max',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Montant maximum de cashback crédité par commande. 0 = pas de plafond.', max_digits=10, verbose_name='Plafond cashback par commande (HTG)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='parrainage_bonus_montant_max',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Montant maximum du bonus de parrainage (par personne). 0 = pas de plafond.', max_digits=10, verbose_name='Plafond bonus parrainage (HTG)'),
        ),
    ]
