# Generated by Django 5.2.12 on 2026-07-17 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_sitesettings_cashback_montant_max_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='android_apk_url',
            field=models.URLField(blank=True, default='', help_text="URL directe de l'APK (ex. GitHub Releases : …/releases/latest/download/maket-peyizan.apk). Prioritaire sur le fichier téléversé — pointez sur /latest/ pour ne plus retoucher la config à chaque version.", verbose_name='Lien de téléchargement Android (URL)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='ios_app_url',
            field=models.URLField(blank=True, default='', help_text="URL de l'application iOS. Vide : le bouton iOS n'apparaît pas sur le site.", verbose_name='Lien iOS (App Store / TestFlight)'),
        ),
    ]
