# Generated by Django 5.1 on 2026-03-24 10:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('catalog', '0001_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgrammeVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('code_programme', models.CharField(max_length=50, unique=True)),
                ('type_programme', models.CharField(choices=[('ong', 'Organisation Non Gouvernementale'), ('gouv', 'Programme gouvernemental'), ('coop', 'Cooperative agricole'), ('entreprise', 'Entreprise privee')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='vouchers/logos/')),
                ('contact_nom', models.CharField(blank=True, max_length=200)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_tel', models.CharField(blank=True, max_length=20)),
                ('budget_total', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('budget_utilise', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('is_active', models.BooleanField(default=True)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Programme Voucher',
                'verbose_name_plural': 'Programmes Voucher',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=100, unique=True)),
                ('type_paiement', models.CharField(choices=[('moncash', 'MonCash'), ('natcash', 'NatCash'), ('virement', 'Virement bancaire'), ('cash', 'Especes'), ('voucher', 'e-Voucher')], max_length=20)),
                ('statut', models.CharField(choices=[('initie', 'Initie'), ('en_attente', 'En attente'), ('soumis', 'Preuve soumise'), ('verifie', 'Verifie'), ('confirme', 'Confirme'), ('echoue', 'Echoue'), ('annule', 'Annule'), ('rembourse', 'Rembourse')], default='initie', max_length=20)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('montant_recu', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('numero_expediteur', models.CharField(blank=True, max_length=20)),
                ('id_transaction', models.CharField(blank=True, max_length=100)),
                ('preuve_image', models.ImageField(blank=True, null=True, upload_to='paiements/preuves/')),
                ('notes', models.TextField(blank=True)),
                ('note_verification', models.TextField(blank=True)),
                ('date_verification', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paiements', to='orders.commande')),
                ('effectue_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_effectues', to=settings.AUTH_USER_MODEL)),
                ('verifie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paiements_verifies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=20, unique=True)),
                ('type_valeur', models.CharField(choices=[('fixe', 'Montant fixe'), ('pourcent', 'Pourcentage de reduction')], default='fixe', max_length=10)),
                ('valeur', models.DecimalField(decimal_places=2, max_digits=10)),
                ('montant_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('montant_commande_min', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('utilise', 'Utilise'), ('expire', 'Expire'), ('annule', 'Annule'), ('suspendu', 'Suspendu')], default='actif', max_length=10)),
                ('date_expiration', models.DateField()),
                ('date_utilisation', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('beneficiaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vouchers', to='accounts.acheteur')),
                ('categories_autorisees', models.ManyToManyField(blank=True, to='catalog.categorie')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vouchers_crees', to=settings.AUTH_USER_MODEL)),
                ('programme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vouchers', to='payments.programmevoucher')),
            ],
            options={
                'verbose_name': 'Voucher',
                'verbose_name_plural': 'Vouchers',
                'ordering': ['-created_at'],
            },
        ),
    ]
