# Generated by Django 5.2.12 on 2026-07-07 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='type_paiement',
            field=models.CharField(choices=[('moncash', 'MonCash'), ('natcash', 'NatCash'), ('virement', 'Virement bancaire'), ('cash', 'Especes'), ('voucher', 'e-Voucher'), ('wallet', 'Portefeuille')], max_length=20),
        ),
    ]
