from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('',                        views.home,                name='index'),
    path('health/',                 views.health_check,        name='health_check'),
    path('connexion/',              views.login_page,          name='login'),
    path('inscription/',            views.register_page,       name='register'),
    path('inscription/en-attente/', views.register_pending,    name='register_pending'),
    path('dashboard/',              views.dashboard_router,    name='dashboard'),
    path('dashboard/acheteur/',              views.dashboard_acheteur,           name='dashboard_acheteur'),
    path('dashboard/acheteur/commandes/',    views.dashboard_acheteur_commandes, name='dashboard_acheteur_commandes'),
    path('dashboard/acheteur/adresses/',     views.dashboard_acheteur_adresses,  name='dashboard_acheteur_adresses'),
    path('dashboard/acheteur/profil/',       views.dashboard_acheteur_profil,    name='dashboard_acheteur_profil'),
    path('dashboard/acheteur/vouchers/',     views.dashboard_acheteur_vouchers,  name='dashboard_acheteur_vouchers'),
    path('dashboard/producteur/',                 views.dashboard_producteur,             name='dashboard_producteur'),
    path('dashboard/producteur/commandes/',       views.dashboard_producteur_commandes,   name='dashboard_producteur_commandes'),
    path('dashboard/producteur/collectes/',       views.dashboard_producteur_collectes,   name='dashboard_producteur_collectes'),
    path('dashboard/producteur/catalogue/',       views.dashboard_producteur_catalogue,   name='dashboard_producteur_catalogue'),
    path('dashboard/producteur/profil/',          views.dashboard_producteur_profil,      name='dashboard_producteur_profil'),
    path('dashboard/producteur/en-attente/',     views.dashboard_producteur_en_attente,  name='dashboard_producteur_en_attente'),
    path('dashboard/producteur/rapport/',        views.dashboard_producteur_rapport,     name='dashboard_producteur_rapport'),
    path('dashboard/admin/',        views.dashboard_admin,     name='dashboard_admin'),
    path('dashboard/superadmin/',                    views.dashboard_superadmin,                  name='dashboard_superadmin'),
    path('dashboard/superadmin/utilisateurs/',       views.dashboard_superadmin_utilisateurs,      name='dashboard_superadmin_utilisateurs'),
    path('dashboard/superadmin/producteurs/',        views.dashboard_superadmin_producteurs,       name='dashboard_superadmin_producteurs'),
    path('dashboard/superadmin/commandes/',          views.dashboard_superadmin_commandes,         name='dashboard_superadmin_commandes'),
    path('dashboard/superadmin/paiements/',          views.dashboard_superadmin_paiements,         name='dashboard_superadmin_paiements'),
    path('dashboard/superadmin/catalogue/',          views.dashboard_superadmin_catalogue,         name='dashboard_superadmin_catalogue'),
    path('dashboard/superadmin/stocks/',             views.dashboard_superadmin_stocks,            name='dashboard_superadmin_stocks'),
    path('dashboard/superadmin/collectes/',          views.dashboard_superadmin_collectes,         name='dashboard_superadmin_collectes'),
    path('dashboard/superadmin/acheteurs/',          views.dashboard_superadmin_acheteurs,         name='dashboard_superadmin_acheteurs'),
    path('dashboard/superadmin/adresses/',           views.dashboard_superadmin_adresses,          name='dashboard_superadmin_adresses'),
    path('dashboard/superadmin/categories/',         views.dashboard_superadmin_categories,        name='dashboard_superadmin_categories'),
    path('dashboard/superadmin/vouchers/',           views.dashboard_superadmin_vouchers,          name='dashboard_superadmin_vouchers'),
    path('dashboard/superadmin/zones/',              views.dashboard_superadmin_zones,             name='dashboard_superadmin_zones'),
    path('dashboard/superadmin/slider/',             views.dashboard_superadmin_slider,            name='dashboard_superadmin_slider'),
    path('dashboard/superadmin/config/',             views.dashboard_superadmin_config,            name='dashboard_superadmin_config'),
    path('dashboard/superadmin/rapport/',            views.dashboard_superadmin_rapport,           name='dashboard_superadmin_rapport'),
    path('dashboard/superadmin/profil/',             views.dashboard_superadmin_profil,            name='dashboard_superadmin_profil'),
    path('dashboard/superadmin/carte/',              views.dashboard_superadmin_carte,             name='dashboard_superadmin_carte'),
    # Catalogue public
    path('produits/<slug:slug>/',   views.produit_detail,      name='produit_detail'),
    path('panier/',                 views.panier_page,         name='panier'),
    path('commander/',                   views.checkout_page,   name='checkout'),
    path('commander/paiement/retour/',   views.paiement_retour, name='paiement_retour'),
    path('commander/moncash/retour/',    views.paiement_retour, name='moncash_retour'),  # rétrocompat
]
