# Generated by Django 5.2.12 on 2026-07-07 13:35

import apps.wallet.utils
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0005_panier_lignepanier_delete_panieritem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BonCadeau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=apps.wallet.utils.generer_code_bon_cadeau, max_length=20, unique=True)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant (HTG)')),
                ('statut', models.CharField(choices=[('attente_paiement', 'En attente de paiement'), ('actif', 'Actif'), ('utilise', 'Utilisé'), ('expire', 'Expiré'), ('annule', 'Annulé')], default='attente_paiement', max_length=20)),
                ('email_destinataire', models.EmailField(blank=True, default='', help_text="Email du destinataire — le code lui est envoyé à l'activation. Vide : le code est envoyé à l'acheteur.", max_length=254)),
                ('message_destinataire', models.CharField(blank=True, default='', max_length=255)),
                ('date_encaissement', models.DateTimeField(blank=True, null=True)),
                ('date_expiration', models.DateTimeField(blank=True, null=True)),
                ('reference_plopplop', models.CharField(blank=True, help_text='Référence envoyée à Plopplop (format GFT{id}-{uuid8}).', max_length=64, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('achete_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bons_cadeaux_achetes', to=settings.AUTH_USER_MODEL)),
                ('encaisse_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bons_cadeaux_encaisses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bon cadeau',
                'verbose_name_plural': 'Bons cadeaux',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solde', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Solde (HTG)')),
                ('is_active', models.BooleanField(default=True, help_text='Désactiver pour bloquer les paiements, recharges et retraits de cet utilisateur.', verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Portefeuille',
                'verbose_name_plural': 'Portefeuilles',
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('recharge', 'Recharge'), ('paiement', 'Paiement commande'), ('remboursement', 'Remboursement'), ('liberation_reserve', 'Libération solde réservé'), ('vente', 'Vente créditée (producteur)'), ('reprise_vente', 'Reprise vente (commande annulée)'), ('retrait', 'Retrait'), ('reprise_retrait', 'Retrait rejeté (re-crédit)'), ('cashback', 'Cashback fidélité'), ('reprise_cashback', 'Reprise cashback'), ('bonus_parrainage', 'Bonus parrainage'), ('reprise_bonus_parrainage', 'Reprise bonus parrainage'), ('bon_cadeau_achat', 'Achat bon cadeau'), ('bon_cadeau_encaisse', 'Bon cadeau encaissé'), ('ajustement', 'Ajustement manuel')], max_length=30)),
                ('montant', models.DecimalField(decimal_places=2, help_text='Montant signé : positif = crédit, négatif = débit.', max_digits=12)),
                ('solde_apres', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Solde après')),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('reference', models.CharField(blank=True, default='', help_text='Référence externe (transaction Plopplop, référence Paiement...).', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('commande', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_transactions', to='orders.commande')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='wallet.wallet')),
            ],
            options={
                'verbose_name': 'Transaction wallet',
                'verbose_name_plural': 'Transactions wallet',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WalletRetrait',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant (HTG)')),
                ('canal', models.CharField(choices=[('moncash', 'MonCash'), ('natcash', 'NatCash')], max_length=10)),
                ('numero_telephone', models.CharField(help_text='Numéro qui recevra le transfert.', max_length=20, verbose_name='Numéro MonCash/NatCash')),
                ('statut', models.CharField(choices=[('demande', 'Demandé'), ('paye', 'Payé'), ('rejete', 'Rejeté')], default='demande', max_length=10)),
                ('preuve_transfert', models.ImageField(blank=True, help_text="Preuve du transfert effectué par l'admin (capture MonCash/NatCash).", null=True, upload_to='wallet/retraits/')),
                ('note_admin', models.TextField(blank=True, help_text='Motif de rejet ou remarque interne.', verbose_name='Note admin')),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('traite_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retraits_traites', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retraits', to='wallet.wallet')),
                ('transaction', models.OneToOneField(blank=True, help_text='Transaction de débit créée à la demande.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retrait', to='wallet.wallettransaction')),
                ('transaction_reprise', models.OneToOneField(blank=True, help_text='Transaction de re-crédit créée si le retrait est rejeté.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retrait_rejete', to='wallet.wallettransaction')),
            ],
            options={
                'verbose_name': 'Retrait wallet',
                'verbose_name_plural': 'Retraits wallet',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WalletRecharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant (HTG)')),
                ('methode', models.CharField(choices=[('moncash', 'MonCash (Plopplop)'), ('natcash', 'NatCash (Plopplop)'), ('hors_ligne', 'Dépôt hors ligne')], max_length=12)),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('preuve_soumise', 'Preuve soumise'), ('creditee', 'Créditée'), ('rejetee', 'Rejetée'), ('echouee', 'Échouée')], default='en_attente', max_length=16)),
                ('reference_plopplop', models.CharField(blank=True, help_text='Référence envoyée à Plopplop (format WAL{id}-{uuid8}).', max_length=64, null=True, unique=True)),
                ('preuve_image', models.ImageField(blank=True, help_text='Preuve de dépôt pour les recharges hors ligne (JPG/PNG, max 5 MB).', null=True, upload_to='wallet/recharges/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recharges', to='wallet.wallet')),
                ('transaction', models.OneToOneField(blank=True, help_text='Transaction de crédit créée à la confirmation.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recharge', to='wallet.wallettransaction')),
            ],
            options={
                'verbose_name': 'Recharge wallet',
                'verbose_name_plural': 'Recharges wallet',
                'ordering': ['-created_at'],
            },
        ),
    ]
