# Generated by Django 5.2.12 on 2026-07-09 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boncadeau',
            name='rappel_expiration_envoye',
            field=models.BooleanField(default=False, help_text='Email de rappel J-30 avant expiration déjà envoyé (tâche wallet.rappeler_bons_expirant).'),
        ),
    ]
