# Generated by Django 5.2.12 on 2026-07-10 16:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
        ('wallet', '0002_boncadeau_rappel_expiration_envoye'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='pos_sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_transactions', to='pos.possale'),
        ),
        migrations.AlterField(
            model_name='wallettransaction',
            name='type',
            field=models.CharField(choices=[('recharge', 'Recharge'), ('paiement', 'Paiement commande'), ('paiement_pos', 'Paiement vente POS'), ('remboursement', 'Remboursement'), ('liberation_reserve', 'Libération solde réservé'), ('vente', 'Vente créditée (producteur)'), ('reprise_vente', 'Reprise vente (commande annulée)'), ('retrait', 'Retrait'), ('reprise_retrait', 'Retrait rejeté (re-crédit)'), ('cashback', 'Cashback fidélité'), ('reprise_cashback', 'Reprise cashback'), ('bonus_parrainage', 'Bonus parrainage'), ('reprise_bonus_parrainage', 'Reprise bonus parrainage'), ('bon_cadeau_achat', 'Achat bon cadeau'), ('bon_cadeau_encaisse', 'Bon cadeau encaissé'), ('ajustement', 'Ajustement manuel')], max_length=30),
        ),
    ]
