# Generated by Django 5.2.12 on 2026-07-10 23:22

import apps.wallet.models.code_paiement
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
        ('wallet', '0003_wallettransaction_pos_sale_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletCodePaiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=apps.wallet.models.code_paiement.generer_code_6_chiffres, max_length=6, verbose_name='Code')),
                ('expire_le', models.DateTimeField(default=apps.wallet.models.code_paiement.expiration_par_defaut, verbose_name='Expire le')),
                ('utilise', models.BooleanField(default=False, verbose_name='Utilisé')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pos_sale', models.ForeignKey(blank=True, help_text="Renseigné à l'utilisation du code.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='codes_paiement', to='pos.possale', verbose_name='Vente POS')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes_paiement_wallet', to=settings.AUTH_USER_MODEL, verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Code de paiement wallet',
                'verbose_name_plural': 'Codes de paiement wallet',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['code', 'utilise'], name='wallet_wall_code_73cdd5_idx')],
            },
        ),
    ]
