# Generated by Django 5.1 on 2026-03-24 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/images/')),
                ('icone', models.CharField(blank=True, help_text='Classe Font Awesome ex: fas fa-carrot', max_length=50)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sous_categories', to='catalog.categorie')),
            ],
            options={
                'verbose_name': 'Categorie',
                'verbose_name_plural': 'Categories',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('description', models.TextField(blank=True)),
                ('variete', models.CharField(blank=True, max_length=100)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prix_gros', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('unite_vente', models.CharField(choices=[('kg', 'Kilogramme (kg)'), ('tonne', 'Tonne'), ('sac_50', 'Sac 50 kg'), ('sac_25', 'Sac 25 kg'), ('botte', 'Botte'), ('piece', 'Piece'), ('litre', 'Litre'), ('carton', 'Carton'), ('douz', 'Douzaine')], default='kg', max_length=20)),
                ('quantite_min_commande', models.PositiveIntegerField(default=1)),
                ('stock_disponible', models.PositiveIntegerField(default=0)),
                ('seuil_alerte', models.PositiveIntegerField(default=10)),
                ('stock_reserve', models.PositiveIntegerField(default=0)),
                ('image_principale', models.ImageField(blank=True, null=True, upload_to='produits/images/')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='produits/qrcodes/')),
                ('origine', models.CharField(blank=True, max_length=200)),
                ('saison', models.CharField(blank=True, max_length=100)),
                ('certifications', models.CharField(blank=True, max_length=200)),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('en_attente', 'En attente de validation'), ('actif', 'Actif'), ('epuise', 'Epuise'), ('inactif', 'Inactif')], default='en_attente', max_length=20)),
                ('is_active', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produits', to='catalog.categorie')),
                ('producteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='accounts.producteur')),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImageProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='produits/galerie/')),
                ('legende', models.CharField(blank=True, max_length=200)),
                ('ordre', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.produit')),
            ],
            options={
                'verbose_name': 'Image produit',
                'verbose_name_plural': 'Images produit',
                'ordering': ['ordre'],
            },
        ),
    ]
