# Generated by Django 5.2.12 on 2026-07-10 16:20

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('stock', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='POSDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_uid', models.CharField(help_text='Identifiant matériel unique du terminal (généré côté application).', max_length=64, unique=True, verbose_name='Identifiant du terminal')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('departement', models.CharField(choices=[('ouest', 'Ouest'), ('sud_est', 'Sud-Est'), ('nord', 'Nord'), ('nord_est', 'Nord-Est'), ('artibonite', 'Artibonite'), ('centre', 'Centre'), ('sud', 'Sud'), ('grand_anse', 'Grand-Anse'), ('nord_ouest', 'Nord-Ouest'), ('nippes', 'Nippes')], max_length=20, verbose_name='Département')),
                ('commune', models.CharField(max_length=100, verbose_name='Commune')),
                ('section_communale', models.CharField(blank=True, max_length=150, verbose_name='Section communale')),
                ('adresse_detail', models.CharField(blank=True, help_text='Ex : Marché Croix-des-Bossales, stand 12', max_length=255, verbose_name='Précision du lieu')),
                ('is_active', models.BooleanField(default=True, help_text='Désactiver pour révoquer un terminal perdu ou volé.', verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pos_devices', to=settings.AUTH_USER_MODEL, verbose_name='Opérateur')),
            ],
            options={
                'verbose_name': 'Terminal POS',
                'verbose_name_plural': 'Terminaux POS',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='POSSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idempotency_key', models.UUIDField(default=uuid.uuid4, help_text='Générée côté client — une resoumission renvoie la vente existante.', unique=True, verbose_name="Clé d'idempotence")),
                ('numero_vente', models.CharField(blank=True, max_length=30, unique=True, verbose_name='Numéro de vente')),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant total (HTG)')),
                ('methode_paiement', models.CharField(choices=[('moncash', 'MonCash'), ('natcash', 'NatCash'), ('cash', 'Especes'), ('voucher', 'e-Voucher'), ('wallet', 'Portefeuille')], max_length=20, verbose_name='Méthode de paiement')),
                ('montant_wallet', models.DecimalField(decimal_places=2, default=0, help_text='Paiement hybride wallet + cash.', max_digits=12, verbose_name='Part payée par wallet (HTG)')),
                ('statut', models.CharField(choices=[('confirmee', 'Confirmée'), ('annulee', 'Annulée')], default='confirmee', max_length=20, verbose_name='Statut')),
                ('stock_conflict', models.BooleanField(default=False, help_text='Vente synchronisée alors que le stock serveur était insuffisant — à arbitrer par le superadmin.', verbose_name='Conflit de stock')),
                ('vendue_le', models.DateTimeField(help_text='Horodatage réel de la vente, fourni par le terminal (ventes offline synchronisées plus tard).', verbose_name='Vendue le')),
                ('synced_le', models.DateTimeField(auto_now_add=True, verbose_name='Synchronisée le')),
                ('client', models.ForeignKey(blank=True, help_text='Acheteur identifié par téléphone/email — vide : vente anonyme.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='achats_pos', to=settings.AUTH_USER_MODEL, verbose_name='Client')),
                ('operateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventes_pos', to=settings.AUTH_USER_MODEL, verbose_name='Opérateur')),
            ],
            options={
                'verbose_name': 'Vente POS',
                'verbose_name_plural': 'Ventes POS',
                'ordering': ['-vendue_le'],
            },
        ),
        migrations.CreateModel(
            name='POSItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(verbose_name='Quantité')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Prix unitaire appliqué (HTG)')),
                ('sous_total', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Sous-total (HTG)')),
                ('lot', models.ForeignKey(blank=True, help_text='Vide : le lot disponible le plus ancien est décrémenté (FIFO).', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ventes_pos', to='stock.lot', verbose_name='Lot')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventes_pos', to='catalog.produit', verbose_name='Produit')),
                ('vente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pos.possale', verbose_name='Vente')),
            ],
            options={
                'verbose_name': 'Ligne de vente POS',
                'verbose_name_plural': 'Lignes de vente POS',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='POSSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fonds_ouverture', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Fonds de caisse initial (HTG)')),
                ('fonds_fermeture', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Comptage à la clôture (HTG)')),
                ('ecart_caisse', models.DecimalField(blank=True, decimal_places=2, help_text='fonds_fermeture − (fonds_ouverture + ventes cash de la session).', max_digits=12, null=True, verbose_name='Écart de caisse (HTG)')),
                ('ouverte_le', models.DateTimeField(auto_now_add=True, verbose_name='Ouverte le')),
                ('fermee_le', models.DateTimeField(blank=True, null=True, verbose_name='Fermée le')),
                ('statut', models.CharField(choices=[('ouverte', 'Ouverte'), ('fermee', 'Fermée')], default='ouverte', max_length=20, verbose_name='Statut')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='pos.posdevice', verbose_name='Terminal')),
                ('operateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pos_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Opérateur')),
            ],
            options={
                'verbose_name': 'Session de caisse',
                'verbose_name_plural': 'Sessions de caisse',
                'ordering': ['-ouverte_le'],
            },
        ),
        migrations.AddField(
            model_name='possale',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventes', to='pos.possession', verbose_name='Session'),
        ),
    ]
